export const Questions = [
  {
    prompt: "What is 2+3?",
    optionA: "23",
    optionB: "32",
    optionC: "1",
    optionD: "5",
    answer: "D",
  },
  {
    prompt: "What is the capital of France?",
    optionA: "Berlin",
    optionB: "Madrid",
    optionC: "Paris",
    optionD: "Rome",
    answer: "C",
  },
  {
    prompt: "Which planet is known as the Red Planet?",
    optionA: "Venus",
    optionB: "Mars",
    optionC: "Jupiter",
    optionD: "Saturn",
    answer: "B",
  },
  // {
  //   prompt: "Who was the first President of the United States?",
  //   optionA: "Thomas Jefferson",
  //   optionB: "George Washington",
  //   optionC: "Abraham Lincoln",
  //   optionD: "John Adams",
  //   answer: "B",
  // },
  // {
  //   prompt: "Which is the largest ocean on Earth?",
  //   optionA: "Atlantic Ocean",
  //   optionB: "Indian Ocean",
  //   optionC: "Arctic Ocean",
  //   optionD: "Pacific Ocean",
  //   answer: "D",
  // },
  // {
  //   prompt: "What is the longest river in the world?",
  //   optionA: "Nile",
  //   optionB: "Amazon",
  //   optionC: "Yangtze",
  //   optionD: "Mississippi",
  //   answer: "A",
  // },
  // {
  //   prompt: "Who painted the Mona Lisa?",
  //   optionA: "Vincent van Gogh",
  //   optionB: "Pablo Picasso",
  //   optionC: "Leonardo da Vinci",
  //   optionD: "Claude Monet",
  //   answer: "C",
  // },
  // {
  //   prompt: "Which element has the chemical symbol 'O'?",
  //   optionA: "Oxygen",
  //   optionB: "Gold",
  //   optionC: "Osmium",
  //   optionD: "Oganesson",
  //   answer: "A",
  // },
  // {
  //   prompt: "What is the largest mammal in the world?",
  //   optionA: "Elephant",
  //   optionB: "Blue Whale",
  //   optionC: "Giraffe",
  //   optionD: "Hippopotamus",
  //   answer: "B",
  // },
  // {
  //   prompt: "Which continent is the largest by land area?",
  //   optionA: "Africa",
  //   optionB: "Asia",
  //   optionC: "Europe",
  //   optionD: "North America",
  //   answer: "B",
  // },
];
